- name: deploy_file
  hosts: all
  user: root
  gather_facts: no
  ignore_errors: yes
  tasks:
  - name: create file if not available
    copy:
     content: "This is test file from tower" 
     dest: /tmp/at_linux_8_test_tower_17jul2020.txt
