- name: deploy_file
  hosts: all
  #9.84.183.87
  user: root
  gather_facts: no
  tasks:
  - name: create file if not available
    copy:
     content: "This is test file from tower" 
     dest: /tmp/higa4jun.txt
